spring:
  application:
    name: senqi-media-server


  datasource:
    url: jdbc:mysql://localhost:3306/senqi_media?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: codermast
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 10000
jwt:
  secret: MyVerySecretKeyThatIsAtLeast32CharactersLong!
  expiration: 3600000
server:
  port: 8888

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
