spring:
  application:
    name: senqi-pic-server

  datasource:
    url: jdbc:mysql://localhost:3306/senqi_pic?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: codermast
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
